# Generated by Django 3.1.4 on 2020-12-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.TextField(blank=True),
        ),
    ]
