# Generated by Django 3.1.4 on 2020-12-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='size',
        ),
    ]
