# Generated by Django 3.1.4 on 2021-01-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
