# Generated by Django 3.1.4 on 2020-12-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='posted_by',
            new_name='owner',
        ),
    ]
